### ISSUE TITLE
Setting custom error messages?

### ISSUE THREAD

**Issue by silverbucket** [geraintluff/tv4#115]
Hello, I was wondering how I could give the user better error messages in certain cases. For example, some parameters need to be floats, in order to validate for this my schema looks like:

``` javascript:
            'lat' : {
              'type' : 'number',
              'not': {
                'multipleOf':1
              }
            },
            'lng' : {
              'type' : 'number',
              'not': {
                'multipleOf':1
              }
            }
```

When i send a string, the error message generated is:

`invalid type: string (expected number)`

When I send a number, the error message generated is:

`Data matches schema from "not"`

This will be very confusing to someone who doesn't know I'm expecting a float. Are there any ways to handle this within the schema definition (setting a custom error message for failures on a specific property?) Or any work-arounds?

**Comment by keshavwork** [comment]
{
  title: "Name",
  type: "String",
  minLength: 4,
  maxLength: 6
  messages: {
    minLength: "Your name must be at least "dynamic value" characters long.",
    maxLengh: "Your name must be no more than six characters long"
  }
}

example : dynamic value( 1,2....);
in above example i need small change any one help me for this

**Comment by johnmanko** [comment]
Was anything ever done with this?  It was closed without an explanation.

**Comment by Philmod** [comment]
Echoing this. I'd love to set my own custom error messages within the schema.

**Comment by johnmanko** [comment]
@silverbucket if you open this I'll work on it.

**Comment by johnmanko** [comment]
@silverbucket I have a branch ready for your review.  Even if you don't accept it I'd like your input.  Thanks.  :)

**Comment by silverbucket** [comment]
@johnmanko well I'm not the maintainer(@geraintluff is), it's not my call, but I'd be happy to have a look. Where is it?

**Comment by johnmanko** [comment]
@silverbucket I'm new to Github (kinda), so you'll have to forgive my lack of branch/fork/git understanding. I cloned this repo locally, and then created a branch.  Unfortunately, it was then I realized I can't just push this branch back to this repo without being added by @geraintluff.  Should I instead fork this project and push my changes there for your review?  Here is a preview:

New `pluck` function in `source/validate.js`:

```javascript
function pluck(schema, key, fallback) {
	return (schema.messages && schema.messages[key]) ? schema.messages[key] : fallback || {};
}
```
Usage in `source/string.js`:
```javascript
ValidatorContext.prototype.validateStringLength = function validateStringLength(data, schema) {
	if (typeof data !== "string") {
		return null;
	}
	if (schema.minLength !== undefined) {
		if (data.length < schema.minLength) {
			return this.createError(ErrorCodes.STRING_LENGTH_SHORT, pluck(schema, "minLength", {length: data.length, minimum: schema.minLength})).prefixWith(null, "minLength");
		}
	}
	if (schema.maxLength !== undefined) {
		if (data.length > schema.maxLength) {
			return this.createError(ErrorCodes.STRING_LENGTH_LONG, pluck(schema, "maxLength", {length: data.length, maximum: schema.maxLength})).prefixWith(null, "maxLength");
		}
	}
	return null;
};
```

**Comment by johnmanko** [comment]
Here is a pull request: https://github.com/geraintluff/tv4/pull/206
Here is an issue I filed with JSON Schema spec team: https://github.com/json-schema/json-schema/issues/183

**Comment by geraintluff** [comment]
Alrighty:

The latest release of tv4 (`v1.2.3`) has the option for custom error reporting:

```javascript
tv4.setErrorReporter(function (error, data, schema) {
    if (error.code === ...) {
        return "Custom error message";
    }
});
```

If you return a falsy value from this function, it will fall back to the default reporter (language templates).

Hopefully this could give you a bit more power when it comes to error reporting.

**Comment by geraintluff** [comment]
So, back to the original query: you can achieve what you want with something like the following:

```javascript
tv4.setErrorReporter(function (error, data, schema) {
    // Last component of schemaPath, which *most* of the time is the keyword!
    var lastSchemaPath = error.schemaPath.split('/').pop();
    return schema.messages && schema.messages[lastSchemaPath];
});
```

To be clear, though, this is a user-specified extension, not part of the spec.

My actual goal (and something I might work on next) is a more intelligent custom error reporter, that can handle things like `{"not": {"multipleOf": 1}}` and give human-readable output, so that this `"messages"` hack is not necessary.

**Comment by silverbucket** [comment]
This is great, thanks a lot @geraintluff !

**Comment by JeremyCraigMartinez** [comment]
hey guys, is there anyway to make this work with a similar example like what @johnmanko posted [here](https://github.com/json-schema/json-schema/issues/183) but instead of `minLength` or `maxLength`, setting the message for a `oneOf` field? Here, I posted a SO question [here](https://stackoverflow.com/questions/37975596/json-schema-ref-to-a-string)

**Comment by airtonix** [comment]
@geraintluff well it's still nessecary when you're using json-schema to validate application forms.

Clients (and non technical users) typically freak out when you return validation errors that do not conversationally explain the problem.

**Comment by johnmanko** [comment]
I filed a spec change at https://github.com/json-schema-org/json-schema-spec/issues/148
