### ISSUE TITLE
validateDefinedKeywords replaces ErrorCodes.INVALID_TYPE with ErrorCodes.KEYWORD_CUSTOM

### ISSUE THREAD

**Issue by sissbruecker** [geraintluff/tv4#178]
If a validation function for a custom keyword returns an error object with the error code for invalid type:
```
{
  ...
  code: tv4.errorCodes.INVALID_TYPE
  ...
}
```
then the validateDefinedKeywords function replaces that error code with the code for custom keywords.

The error is in this line:
```
var code = result.code || ErrorCodes.KEYWORD_CUSTOM;
```

Since tv4.errorCodes.INVALID_TYPE == 0, the first expression fails. Instead the code should check if result.code is undefined.

Same goes for the error code lookup just below that line:
```
if (!ErrorCodes[code]) {
  throw new Error('Undefined error code (use defineError): ' + code);
}
```
which fails for the same reason.

I'm assuming this is a bug and that this behavior is not intentional?

**Comment by geraintluff** [comment]
Hah!  Good catch.

No, that's not deliberate.  I guess it should be `(typeof result.code === 'number') ? result.code || ErrorCodes.KEYWORD_CUSTOM` or similar.

**Comment by geraintluff** [comment]
Actually, out of interest, why are you returning INVALID_TYPE from custom validation?  That error code was designated for a particular type of error, and some tools (e.g. [tv4-coerce](https://github.com/geraintluff/tv4-coerce) or UIs) might depend on the semantics of a particular error code in order to fix it).

**Comment by sissbruecker** [comment]
Hello @geraintluff , thanks for checking in.

I needed a way to apply a schema conditionally, based on the value of a property. Since JSON Schema does not have a method to define constraints based on property values (only on the existence of a property) I decided to try to implement the proposal for the switch keyword as a custom keyword. My implementation for switch in turn uses tv4.validate, thus I'm actually only returning returning errors produced by tv4 itself. The code looks something like this:

```
tv4.defineKeyword('switch', function (data, value, schema) {

    if (!value || !value.length) return;

    for (var i = 0; i < value.length; i++) {

        var switchCase = value[i];
        var applyCase = switchCase.if == undefined || tv4.validate(data, switchCase.if);

        if (applyCase) {

             return tv4.validate(data, switchCase.then) || tv4.error;
        }
    }

    return null;
});
```

This allows me to process schemas like this:
```
'allOf': [
    {'$ref': '#/definitions/baseVariable'},
    {
        'switch': [
            {
                'if': {'properties': {'type': {'enum': ['text']}}},
                'then': {'$ref': '#/definitions/textVariable'}
            },
            {
                'if': {'properties': {'type': {'enum': ['boolean']}}},
                'then': {'$ref': '#/definitions/booleanVariable'}
            },
            {
                'if': {'properties': {'type': {'enum': ['number']}}},
                'then': {'$ref': '#/definitions/numberVariable'}
            }
        ]
    }
]
```

**Comment by geraintluff** [comment]
Ah, implementing the `switch` proposal!  Nice.

I'll get you a fix promptly-ish.

**Comment by geraintluff** [comment]
OK, try giving that a whirl and let me know how it goes.

**Comment by sissbruecker** [comment]
Thanks for the fix, it's working now :)

By the way there still is the second error I mentioned:
```
if (!ErrorCodes[code]) {
	throw new Error('Undefined error code (use defineError): ' + code);
}
```

If someone passes the code as the string "INVALID_TYPE" the above lookup will fail because ErrorCodes["INVALID_TYPE"] is 0. Here you should probably also check if the lookup result is a number.
