### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Imperadeiro98** [geraintluff/tv4#187]
I would like to translate to pt-PT, but I don't know where to start. Could anyone guide me?

**Comment by Exsilium122** [comment]
Look at my pull request:  https://github.com/geraintluff/tv4/pull/189

1. Fork repositor
1. Clone you fork to your computer
1. add your language file with translations to *lang* folder
1. commit and push your changes
1. create pull request in github

**Comment by Imperadeiro98** [comment]
Thank you.
