### ISSUE TITLE
Is it possible to change the license type to MIT 

### ISSUE THREAD

**Issue by mayank-patel** [geraintluff/tv4#199]
Hi, I wanted to use this module in one of my client projects. But since this is Public Domain License I can not do so. Is it possible for you to change it to MIT License please ?

**Comment by mitar** [comment]
What do you mean? If it is public domain, you can do whatever you want to do with it. It is even more permissive than MIT license. Check with your client, they will not have any objection using it.

**Comment by geraintluff** [comment]
It's also available under the MIT license, as mentioned in the README.

If you'd like a branch that's got an MIT license in the LICENSE file, that's also possible.
