### ISSUE TITLE
[Documentation] Validate JSON Schrma

### ISSUE THREAD

**Issue by sathishk** [geraintluff/tv4#209]
Is there any documentation to validate a JSON Schema for the format adherence ?
like 
var isValidSchema = tv4.validate(schema);

**Comment by sathishk** [comment]
I think this is invalid. I can achive this by validating schema object using meta schema https://github.com/json-schema/json-schema/blob/master/draft-04/schema

**Comment by geraintluff** [comment]
Yes, that is the appropriate solution (sorry for not responding promptly).
