### ISSUE TITLE
The "license" json attribute in package.json contains an unexpected extra colon [':'] char in the name

### ISSUE THREAD

**Issue by heespilogic** [geraintluff/tv4#233]
This prevents an automated parser to extract the license information. I'm wondering if this small issue is something that could be addressed as part of an upcoming set of changes. Thanks in advance,

Hector
![packagejsonlicenseextracolon](https://cloud.githubusercontent.com/assets/16070480/15190025/bc84dc42-17a5-11e6-9362-5adfdc6f4ecd.PNG)

**Comment by edi9999** [comment]
Indeed, it would be great to fix this ...
